Responsive Footer, Minor UI Changes on Homepage
iit-technology-ambit/Apsara2.0 pull request #6
Opened 2019-10-20 17:55 UTC by ajajaj2807

2019-10-20 18:52 UTC, rakaar commented
Things look really great now
But @ajajaj2807  there are few more important changes as suggested by Karthik Tyagi. Please make them also in this PR
1.logo width in navbar 54px in desktop view
2.left and right hand side of the navbar should have equal padding of 100px in desktop view
3. Nav icons should not be in upper case, with styling in semi bold and size of 24px in desktop view
4. The IIT Tech ambit logo in the page(not in nav) should be center aligned with the text below with size 100px
5. Body in font should be `Montessarrat`
6.  And input for mail was to be kept as it is in the video

2019-10-21 08:22 UTC, thealphadollar requested changes
Looks really good to me. A few changes and screenshots and we will be good to go.

Thank you for the PR, @ajajaj2807

2019-10-21 08:22 UTC, thealphadollar commented on src/views/Components/Components.scss
>    margin-top: 9% !important;
Why has `!important` been included everywhere? Is there any other way without enforcing it, this is not a good practice?

2019-10-21 08:22 UTC, thealphadollar commented on src/components/Footer/OldFooter.scss
> +    height: max-content !important;
Same issue here.

2019-10-21 08:22 UTC, thealphadollar commented on src/index.js
> -      <Route path='/' component={MobileFooter} />
Please put a screenshot for this.

2019-10-21 08:22 UTC, thealphadollar commented on src/views/Components/Components.js
>              )}
Please put screenshot for these changes. @ajajaj2807

2019-10-23 08:26 UTC, merged